custom_configuration.settings:
  title: "My platforms custom settings"
  description: "Custom settings for my platform."
  parent: system.admin_config_system
  route_name: custom_configuration.settings
  weight: 10
