custom_configuration.settings_form:
  path: "/admin/config/system/custom-configuration"
  defaults:
    _form: '\Drupal\custom_configuration\Form\SettingsForm'
    _title: "Custom Configuration"
  requirements:
    _permission: "administer custom_configuration configuration"
